services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src
